# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#use_frameworks!

target 'Blueshift-iOS-MParticle-SampleApp' do
  pod 'Blueshift-mParticle-Kit'

end

target 'NotificationSer' do
  pod 'BlueShift-iOS-Extension-SDK'
  
end

target 'NotificationContentService' do
  pod 'BlueShift-iOS-Extension-SDK'
    
end
